name: CI
on: push

jobs:
  steamcmd:
    name: Build Docker Image (SteamCMD)
    runs-on: ubuntu-latest
    steps:
      - name: Login to the GitHub Docker Registry
        # language=BASH
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${GITHUB_REPOSITORY%/*} --password-stdin docker.pkg.github.com
      - uses: actions/checkout@v1
      - name: Build Docker image
        # language=BASH
        run: >-
          docker build
          --pull
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/steamcmd:$(GITHUB_REF=${GITHUB_REF#refs/heads/}; echo -n ${GITHUB_REF////-})"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/steamcmd:$(date +%s)"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/steamcmd:$GITHUB_SHA"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/steamcmd:${GITHUB_SHA:0:7}"
          ./steamcmd/
      - name: Publish Docker image to GitHub Package Registry
        # language=BASH
        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/steamcmd"
