name: SteamCMD Docker Image
on:
  push:
    paths:
      - source-engine/*

jobs:
  steamcmd:
    name: Build Docker Image (Insurgency)
    runs-on: ubuntu-latest
    steps:
      - name: Login to the GitHub Docker Registry
        # language=BASH
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${GITHUB_REPOSITORY%/*} --password-stdin docker.pkg.github.com
      - uses: actions/checkout@v1
      - name: Build Docker image
        # language=BASH
        run: >-
          docker build
          --build-arg GAME_SLUG=insurgency
          --build-arg GAME_APPID=237410
          --pull
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/insurgency:$(GITHUB_REF=${GITHUB_REF#refs/heads/}; echo -n ${GITHUB_REF////-})"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/insurgency:$(date +%s)"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/insurgency:$GITHUB_SHA"
          --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/insurgency:${GITHUB_SHA:0:7}"
          ./source-engine/
      - name: Publish Docker image to GitHub Package Registry
        # language=BASH
        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/insurgency"
